### ISSUE TITLE
Not working after installation, pre-requisites met, installation done properly

### ISSUE THREAD

**Issue by sneader** [letsencrypt-cpanel/letsencrypt-cpanel-dnsonly#1]
Not working after installation. running latest DNS Only, server has FQDN (can go to https://my.hostname.tld:2087 to log into the DNS Only server.

When the daily cron runs, the cron output is sent via email, and contains:

20171117222715 [ERROR] acme.storageops: could not obtain authorization for my.hostname.tld: failed all combinations
20171117222715 [ERROR] acme.storageops: Target(my.hostname.tld;https://acme-v01.api.letsencrypt.org/directory;0): failed to request certificate: failed all combinations
20171117222715 [ERROR] acme.storageops: error while processing targets: the following errors occurred:
error satisfying Target(my.hostname.tld;https://acme-v01.api.letsencrypt.org/directory;0): failed all combinations
20171117222715 [ERROR] acme.storageops: failed to reconcile: the following errors occurred:
error satisfying Target(my.hostname.tld;https://acme-v01.api.letsencrypt.org/directory;0): failed all combinations
20171117222715 [CRITICAL] acmetool: fatal: reconcile: the following errors occurred:
error satisfying Target(my.hostname.tld;https://acme-v01.api.letsencrypt.org/directory;0): failed all combinations

The actual FQDN hostname has been redacted to my.hostname.tld

**Comment by alexzorin** [comment]
You can run the reconcile command with higher level logging for additional information:

```
/usr/local/letsencrypt-cpanel-dnsonly/acmetool --xlog.severity=debug reconcile
```

You should be able to see whether the listener starts on port 80 and whether Let's Encrypt was able to connect to it.

Please keep in mind that isn't a support channel and we won't provide troubleshooting for the acmetool project:

> I need help. This project is community supported. This means, you may not email us at FleetSSL about it - sorry, we are not providing technical support! You may open an issue on the Github project if you believe you have found a bug or you would like to contribute code or documentation.

**Comment by sneader** [comment]
Thanks, Alex.  Your debug option worked great to pinpoint the issue. Would you be willing to add that command to the Usage part of the instructions at https://dnsonly.letsencrypt-for-cpanel.com/?
