### ISSUE TITLE
Error 404 - Unable to install or update via yum

### ISSUE THREAD

**Issue by IT-Dave** [letsencrypt-cpanel/letsencrypt-cpanel-dnsonly#11]
After doing a 'yum clean all' i am now getting these "HTTPS Error 404 - Not Found" error messages over all four of our DNS servers. I have had this issue for over a week now. Please see attached Error and the yum-config-manager --enable letsencrypt-cpanel settings.

[root@ns1 ~]# yum update
Loaded plugins: fastestmirror, universal-hooks
Loading mirror speeds from cached hostfile
 * EA4: 103.223.184.12
 * cpanel-addons-production-feed: 103.223.184.12
 * cpanel-plugins: 103.223.184.12
 * base: ftp.swin.edu.au
 * epel: mirror.realcompute.io
 * extras: ftp.swin.edu.au
 * updates: ftp.swin.edu.au
letsencrypt-cpanel                                                                                                                                                                                                    | 2.9 kB  00:00:00
letsencrypt-cpanel/primary_db  FAILED
https://r.cpanel.fleetssl.com/repodata/e0ae807b589ffbec3c4fc161d59444ffcd6fdd32c8944f6ebf6c99c6a05df482-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found                                         ]  0.0 B/s |    0 B  --:--:-- ETA
Trying other mirror.
To address this issue please refer to the below wiki article

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.

letsencrypt-cpanel/primary_db  FAILED
https://r.cpanel.fleetssl.com/repodata/e0ae807b589ffbec3c4fc161d59444ffcd6fdd32c8944f6ebf6c99c6a05df482-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found                                         ]  0.0 B/s |    0 B  --:--:-- ETA
Trying other mirror.
https://r.cpanel.fleetssl.com/repodata/e0ae807b589ffbec3c4fc161d59444ffcd6fdd32c8944f6ebf6c99c6a05df482-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.

 One of the configured repositories failed (Let's Encrypt for cPanel),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=letsencrypt-cpanel ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable letsencrypt-cpanel
        or
            subscription-manager repos --disable=letsencrypt-cpanel

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=letsencrypt-cpanel.skip_if_unavailable=true

failure: repodata/e0ae807b589ffbec3c4fc161d59444ffcd6fdd32c8944f6ebf6c99c6a05df482-primary.sqlite.bz2 from letsencrypt-cpanel: [Errno 256] No more mirrors to try.
https://r.cpanel.fleetssl.com/repodata/e0ae807b589ffbec3c4fc161d59444ffcd6fdd32c8944f6ebf6c99c6a05df482-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
[root@ns1 ~]#

[root@ns1 ~]# yum-config-manager --enable letsencrypt-cpanel
Loaded plugins: fastestmirror
========================================================================================================= repo: letsencrypt-cpanel ==========================================================================================================
[letsencrypt-cpanel]
async = True
bandwidth = 0
base_persistdir = /var/lib/yum/repos/x86_64/7
baseurl = https://r.cpanel.fleetssl.com
cache = 0
cachedir = /var/cache/yum/x86_64/7/letsencrypt-cpanel
check_config_file_age = True
compare_providers_priority = 80
cost = 1000
deltarpm_metadata_percentage = 100
deltarpm_percentage =
enabled = 1
enablegroups = True
exclude =
failovermethod = priority
ftp_disable_epsv = False
gpgcadir = /var/lib/yum/repos/x86_64/7/letsencrypt-cpanel/gpgcadir
gpgcakey =
gpgcheck = False
gpgdir = /var/lib/yum/repos/x86_64/7/letsencrypt-cpanel/gpgdir
gpgkey =
hdrdir = /var/cache/yum/x86_64/7/letsencrypt-cpanel/headers
http_caching = all
includepkgs =
ip_resolve =
keepalive = True
keepcache = False
mddownloadpolicy = sqlite
mdpolicy = group:small
mediaid =
metadata_expire = 21600
metadata_expire_filter = read-only:present
metalink =
minrate = 0
mirrorlist =
mirrorlist_expire = 86400
name = Let's Encrypt for cPanel
old_base_cache_dir =
password =
persistdir = /var/lib/yum/repos/x86_64/7/letsencrypt-cpanel
pkgdir = /var/cache/yum/x86_64/7/letsencrypt-cpanel/packages
proxy = False
proxy_dict =
proxy_password =
proxy_username =
repo_gpgcheck = False
retries = 10
skip_if_unavailable = False
ssl_check_cert_permissions = True
sslcacert =
sslclientcert =
sslclientkey =
sslverify = True
throttle = 0
timeout = 30.0
ui_id = letsencrypt-cpanel
ui_repoid_vars = releasever,
   basearch
username =

**Comment by alexzorin** [comment]
Sorry! Give it another shot.
