### ISSUE TITLE
Nothing happens on cPanel v80+

### ISSUE THREAD

**Issue by MarceloPedra** [letsencrypt-cpanel/letsencrypt-cpanel-dnsonly#12]
I followed the website instructions, and no cert was generated or installed.
No error messages. Just ok messages, but nothing happenned.
Have you tried the script on cPanel 80?

**Comment by alexzorin** [comment]
>  Have you tried the script on cPanel 80?

Yes, I installed a blank DNSONLY v80 right now and it issues and installs a certificate as expected.

See the troubleshooting command under "Usage" on the website.

**Comment by alexzorin** [comment]
Closing as invalid for now, please post the output of the debugging command if you wish to revisit this.
