### ISSUE TITLE
error satisfying Target

### ISSUE THREAD

**Issue by theozsnowman** [letsencrypt-cpanel/letsencrypt-cpanel-dnsonly#13]
Ive tried to run this script on my dns only servers and it all runs thru and installs ok but fails at the end.

a debug returns the error:

20190624232959 [CRITICAL] acmetool: fatal: reconcile: the following errors occurred:
error satisfying Target(**server.domain.com.au**;https://acme-v01.api.letsencrypt.org/directory;0): failed all combinations

where server.domain.com.au = my server hostname

**Comment by alexzorin** [comment]
Full, unredacted output of the debug command please.

Edit: I'm going to close this for inactivity, please comment if you wish to revisit it.
