### ISSUE TITLE
/etc/cron.d/fleetssl-dnsonly not executing

### ISSUE THREAD

**Issue by mattgroves** [letsencrypt-cpanel/letsencrypt-cpanel-dnsonly#17]
I have the latest version of letsencrypt-cpanel-dnsonly-1.0.4-1.x86_64 on CentOS7.8 3.10.0-957.1.3.el7.x86_64

Lately, I received continual notifications that the service SSL certificates had not been renewed. Checking /var/log/cron, fleetssl-dnsonly is not executing as it should every twelve hours.

/etc/cron.d/fleetssl-dnsonly contains:

`0 0,12 * * * root python -c 'import random; import time; time.sleep(random.random() * 3600)' && /usr/local/bin/fleetssl-dnsonly`

I've tried reinstalling. Running /usr/local/bin/fleetssl-dnsonly manually works fine. Executing `python -c 'import random; import time; time.sleep(random.random() * 3600)' ` manually works fine.

I don't see any evidence of /etc/cron.d/fleetssl-dnsonly being triggered in the cron log.

Has anyone seen this and/or has a fix other than hacking or removing the default /etc/cron.d/fleetssl-dnsonly entry and adding it to root's crontab?

**Comment by alexzorin** [comment]
Well, #14 reported the same thing, so I do believe it's a real issue. I just don't understand why and the previous reporter disappeared.

Here's my suggestion on helping me to debug this:

1. Change the crontab spec to run every minute, so you don't have to wait ages: `* * * * *`
2. Check if anything happens in the cron log in the next 2 minutes
3. Remove the Python bit, so it's just calling `/usr/local/bin/fleetssl-dnsonly`
4. Check if anything happens in the cron log in the next 2 minutes

That should hopefully get us some hints.

**Comment by mattgroves** [comment]
Thanks @alexzorin - I had tried something similar previously, hence me changing the title.

If I do that, /etc/cron.d/fleetsl-dnsonly now contains (attempting to make it trigger in a few minutes):

`20 * * * * /usr/local/bin/fleetssl-dnsonly`

However, a `service crond reload` results in the following in /var/log/cron:

`May 21 10:18:01 ns1 crond[30498]: (CRON) bad command (/etc/cron.d/fleetssl-dnsonly)`

What I then did was comment the new entry out entirely, effectively disabling /etc/cron.d/fleetssl-dnsonly and added it as root via crontab -e. The result at 20 past the hour:

`May 21 10:20:01 ns1 crond[30498]: (*system*) RELOAD (/etc/cron.d/fleetssl-dnsonly)
May 21 10:20:01 ns1 crond[30498]: (root) RELOAD (/var/spool/cron/root)
May 21 10:20:01 ns1 CROND[29878]: (root) CMD (/usr/lib64/sa/sa1 1 1)
May 21 10:20:01 ns1 CROND[29879]: (root) CMD (/usr/local/bin/fleetssl-dnsonly)`

Therefore it looks like this executed properly, and I received a root cron mail to that effect:

`2020/05/21 10:20:01 fleetssl-dnsonly/1.0.4
2020/05/21 10:20:01 [CONFIG] FLEETSSL_DNSONLY_RENEWAL_CUTOFF=31
2020/05/21 10:20:01 No need to issue a certificate, exiting: certificate is valid and not expiring soon`

I have 2 more servers on which I can conduct testing that still need renewals, if you have further ideas on how to debug the default /etc/cron.d/fleetssl-dnsonly.

**Comment by alexzorin** [comment]
>May 21 10:18:01 ns1 crond[30498]: (CRON) bad command (/etc/cron.d/fleetssl-dnsonly)

Files in `cron.d` have to include the user as a field after the timespec, since it cannot be automatically inferred as in the case of `crontab -e`.

When you deleted the `root` token, the line became invalid. I think that's the reason for the `bad command` message.

**Comment by mattgroves** [comment]
Ah right, with those changes made and a single time trigger at */25 it works fine:

`May 21 11:21:01 ns1 crond[30498]: (*system*) RELOAD (/etc/cron.d/fleetssl-dnsonly)`
`May 21 11:21:01 ns1 crond[30498]: (root) RELOAD (/var/spool/cron/root)`

`May 21 11:25:01 ns1 CROND[4169]: (root) CMD (/usr/local/bin/fleetssl-dnsonly)`

So just the `python ...  &&` command that is interfering?

`[root@ns1 ~]# python -V`
`Python 2.7.5`

Maybe rather we can utilise a shell sleep function instead, something like `sleep ${RANDOM:0:60}m` to achieve the same thing?

**Comment by mattgroves** [comment]
I just confirmed the following works in /etc/cron.d/fleetssl-dnsonly and has no reliance on python, then:

`May 21 11:30:01 ns1 crond[30498]: (*system*) RELOAD (/etc/cron.d/fleetssl-dnsonly)`
`May 21 11:30:01 ns1 CROND[4681]: (root) CMD (sleep ${RANDOM:0:2}m && /usr/local/bin/fleetssl-dnsonly)`
`May 21 11:30:01 ns1 CROND[4682]: (root) CMD (/usr/lib64/sa/sa1 1 1)`

**Comment by alexzorin** [comment]
I had copied the `python` sleep from the Certbot project (i.e. the crontab given on https://certbot.eff.org/lets-encrypt/pip-other) because they had been talking to Let's Encrypt operations about minimizing the thundering herd effect on the CA servers. 

It's really weird that somehow this project surfaces a problem, when Certbot has an unbelievably high number of deployments :\.

I think the problem is probably related to the `$PATH` that your cron daemon executes with. Out of curiosity, could you tell me:

    which python
    grep PATH /etc/crontab

I don't really mind what the sleep command is as long as it's portable, but we may as well figure out the root cause.

**Comment by mattgroves** [comment]
Sure:.

`[root@ns1 ~]# which python`
`/usr/bin/python`
`[root@ns1 ~]# grep PATH /etc/crontab`
`PATH=/sbin:/bin:/usr/sbin:/usr/bin`

I have two different versions running at the moment spawned from cron:

`root      4681  4680  0 11:30 ?        00:00:00 /bin/sh -c sleep ${RANDOM:0:2}m && /usr/local/bin/fleetssl-dnsonly`
`root      4683  4681  0 11:30 ?        00:00:00 sleep 10m`
`root      5085  5082  0 11:33 ?        00:00:00 /bin/sh -c sleep ${RANDOM:0:2}m ; /usr/local/bin/fleetssl-dnsonly`
`root      5087  5085  0 11:33 ?        00:00:00 sleep 23m`

**Comment by alexzorin** [comment]
Ah, stupid mistake. I never included a `PATH` in the `cron.d` file, which of course is necessary in order to be portable (it is not necessarily inherited from anywhere like `/etc/crontab`).

So if you restore the original version and put this at the top:

    SHELL=/bin/sh
    PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

everything should work. I'll merge a fix and tag a release tomorrow.

**Comment by mattgroves** [comment]
OK great, I've made that change:

    SHELL=/bin/sh
    PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
    59 * * * * root python -c 'import random; import time; time.sleep(random.random() * 3600)' && /usr/local/bin/fleetssl-dnsonly

At 14:59 SAST it executed successfully (previously it wouldn't have even logged this):

    May 21 12:57:01 ns1 crond[30498]: (*system*) RELOAD (/etc/cron.d/fleetssl-dnsonly)
    May 21 12:57:01 ns1 crond[30498]: (CRON) INFO (running with inotify support)
    May 21 12:59:01 ns1 CROND[13841]: (root) CMD (python -c 'import random; import time; time.sleep(random.random() * 3600)' && /usr/local/bin/fleetssl-dnsonly)

I'll wait for the fix and then update from repo?

Thanks for the rapid support.
