### ISSUE TITLE
AlmaLinux

### ISSUE THREAD

**Issue by Tntdruid** [letsencrypt-cpanel/letsencrypt-cpanel-dnsonly#18]
Hello,

Any plan to add support for that os?

It's the os for cPanel.

dnf install letsencrypt-cpanel-dnsonly
Last metadata expiration check: 0:07:58 ago on Wed 07 Apr 2021 05:24:45 PM UTC.
Package letsencrypt-cpanel-dnsonly-0.1.1-1.x86_64 is already installed.
Error:
 Problem: cannot install the best candidate for the job
  - nothing provides python needed by letsencrypt-cpanel-dnsonly-1.1.0-1.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

**Comment by alexzorin** [comment]
I hadn't heard the news about AlmaLinux (and Ubuntu), thanks.

It's kind of odd that there is package named `python` in AlmaLinux, but whatever. Fixing this should be pretty simple.

I'll try get to this soon.

**Comment by Tntdruid** [comment]
https://blog.cpanel.com/almalinux-and-full-cpanel-support/
