### ISSUE TITLE
Automatic renewal of an installed certificate

### ISSUE THREAD

**Issue by dimangelid** [letsencrypt-cpanel/letsencrypt-cpanel-dnsonly#5]
Hello,

I need to perform automatic renewal of the certificates i have installed on cPanel DNSONLY servers.

Currently on one server i have setup the below cron job to run as root:

0 0 1 2,5,8,11 /usr/local/letsencrypt-cpanel-dnsonly/acmetool --xlog.severity=debug reconcile >/dev/null 2>&1

The certificate in my example expires on 15th of May 2018 and i have set the renewal at first day each three months.

Is my approach correct? Will cPanel services be restarted automatically to get the renewed certificate? Or you suggest another procedure?

Thank you in advance,
Dimitris

**Comment by alexzorin** [comment]
> Currently on one server i have setup the below cron job to run as root:

acmetool automatically adds its own cronjob in `/etc/cron.d`:

https://github.com/letsencrypt-cpanel/letsencrypt-cpanel-dnsonly/blob/14e20e7edf90e90a4a3a30e31064b1d3b00ced07/responses.yml#L7

For what it's worth, the cron should/does run at least daily. You do not need to worry about the schedule, as acmetool will not do anything until the certificate is approaching the end of its validity.

> Will cPanel services be restarted automatically to get the renewed certificate?

Yes:

https://github.com/letsencrypt-cpanel/letsencrypt-cpanel-dnsonly/blob/14e20e7edf90e90a4a3a30e31064b1d3b00ced07/certificate-hook.sh#L35

You should not need to do ANY further setup after installing the package.
