### ISSUE TITLE
cPanel Services certs

### ISSUE THREAD

**Issue by MACscr** [letsencrypt-cpanel/letsencrypt-cpanel-dnsonly#6]
my DNS only servers are setup as secondary mx servers as well, which Im assuming is the reason why exim and dovecot are running (not 100% sure why dovecot). Anyway, seems as if your tool works great for standard WHM access, but how about making it work with all cPanel services running on the DNS only server?

**Comment by alexzorin** [comment]
Edit: Sorry, I did not properly comprehend your question. Let me setup a DNSONLY server and take a look.

**Comment by alexzorin** [comment]
Well, this looks pretty straightforward. Thanks for the suggestion.

For Exim, it is managed by cPanel in the usual way, so we can add a certificate to it [using the WHM API](https://github.com/letsencrypt-cpanel/letsencrypt-cpanel-dnsonly/commit/6b88aed24f3a66aa738fdbc4840aa286d7de3f6b) as on a regular WHM/cPanel server.

From what I can tell, Dovecot does absolutely nothing (does not bind to any ports), even though it runs. We'll install the certificate to it just-in-case.

@MACscr try upgrading to 0.1.0 and invoking the certificate hook:

```bash
# Upgrade
yum clean all && yum -y install letsencrypt-cpanel-dnsonly
# Invoke hook to re-install certificate to cPanel services
/usr/local/letsencrypt-cpanel-dnsonly/acmetool test-notify $(hostname)
# Check the certificate was installed to Exim SMTPS
openssl s_client -connect $(hostname):465 -servername $(hostname) -showcerts | openssl x509 -noout -issuer -subject
```

**Comment by MACscr** [comment]
Wow, fast and awesome work. I think that worked! hopefully no more ssl reminder emails from my dns cluster now! Thanks!
