### ISSUE TITLE
Installation critical failure on cPanel DNSonly

### ISSUE THREAD

**Issue by CT-NetService** [letsencrypt-cpanel/letsencrypt-cpanel-dnsonly#7]
[root@ns1 ~]# wget https://cpanel.fleetssl.com/static/letsencrypt.repo -O /etc/yum.repos.d/letsencrypt.repo
--2018-07-04 00:29:08--  https://cpanel.fleetssl.com/static/letsencrypt.repo
Resolving cpanel.fleetssl.com (cpanel.fleetssl.com)... 103.209.24.132
Connecting to cpanel.fleetssl.com (cpanel.fleetssl.com)|103.209.24.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 100 [text/plain]
Saving to: ‘/etc/yum.repos.d/letsencrypt.repo’

100%[======================================>] 100         --.-K/s   in 0s

2018-07-04 00:29:10 (11.0 MB/s) - ‘/etc/yum.repos.d/letsencrypt.repo’ saved [100/100]

[root@ns1 ~]# yum -y install letsencrypt-cpanel-dnsonly
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * cpanel-addons-production-feed: 85.13.201.2
 * base: centos.mirrors.ovh.net
 * extras: centos.mirror.fr.planethoster.net
 * updates: centos.mirrors.ovh.net
cpanel-addons-production-feed                            | 2.9 kB     00:00
base                                                     | 3.6 kB     00:00
extras                                                   | 3.4 kB     00:00
letsencrypt-cpanel                                       | 2.9 kB     00:00
updates                                                  | 3.4 kB     00:00
letsencrypt-cpanel/primary_db                              | 9.0 kB   00:00
Resolving Dependencies
--> Running transaction check
---> Package letsencrypt-cpanel-dnsonly.x86_64 0:0.1.0-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package                       Arch      Version    Repository             Size
================================================================================
Installing:
 letsencrypt-cpanel-dnsonly    x86_64    0.1.0-1    letsencrypt-cpanel    4.1 M

Transaction Summary
================================================================================
Install  1 Package

Total download size: 4.1 M
Installed size: 13 M
Downloading packages:
letsencrypt-cpanel-dnsonly-0.1.0-1.x86_64.rpm              | 4.1 MB   00:00
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
ns1.ct-netservice.com has address 54.37.242.61
ns1.ct-netservice.com mail is handled by 0 ns1.ct-netservice.com.
  Installing : letsencrypt-cpanel-dnsonly-0.1.0-1.x86_64                    1/1
!!! Please wait, configuring acmetool !!!
[=======================================================] 100.00% 8s  -]   0.00%

------------------------- Quickstart Complete ----------------------
The quickstart process is complete.

Ensure your chosen challenge conveyance method is configured properly
before attempting to request certificates. You can find more
information about how to configure your system for each method in the
acmetool documentation:
https://github.com/hlandau/acme/blob/master/_doc/WSCONFIG.md

To request a certificate, run:

$ sudo acmetool want example.com www.example.com

If the certificate is successfully obtained, it will be placed in
/var/lib/acme/live/example.com/{cert,chain,fullchain,privkey}.

!!! Please wait, trying to issue certificate now !!!
20180704002938 [ERROR] acme.storageops: could not obtain authorization for ns1.ct-netservice.com: failed all combinations
20180704002938 [ERROR] acme.storageops: Target(ns1.ct-netservice.com;https://acme-v01.api.letsencrypt.org/directory;0): failed to request certificate: failed all combinations
20180704002938 [ERROR] acme.storageops: error while processing targets: the following errors occurred:
error satisfying Target(ns1.ct-netservice.com;https://acme-v01.api.letsencrypt.org/directory;0): failed all combinations
20180704002938 [ERROR] acme.storageops: failed to reconcile: the following errors occurred:
error satisfying Target(ns1.ct-netservice.com;https://acme-v01.api.letsencrypt.org/directory;0): failed all combinations
20180704002938 [CRITICAL] acmetool: fatal: reconcile: the following errors occurred:
error satisfying Target(ns1.ct-netservice.com;https://acme-v01.api.letsencrypt.org/directory;0): failed all combinations
warning: %post(letsencrypt-cpanel-dnsonly-0.1.0-1.x86_64) scriptlet failed, exit status 1
Non-fatal POSTIN scriptlet failure in rpm package letsencrypt-cpanel-dnsonly-0.1.0-1.x86_64
  Verifying  : letsencrypt-cpanel-dnsonly-0.1.0-1.x86_64                    1/1

Installed:
  letsencrypt-cpanel-dnsonly.x86_64 0:0.1.0-1

Complete!

**Comment by alexzorin** [comment]
You have a CAA record that prohibits Let's Encrypt issuing any certificates.

>  ct-netservice.com. 0 IN CAA 0 issue "comodoca.com" 

If you have any further problems, please use the troubleshooting command listed under the *Usage* header in the docs.

**Comment by CT-NetService** [comment]
Please put this on the FleetSSL website, this is easily overlooked. Thanks for the quick reply, I’ll try it again now.




If you need any clarification or have any other questions don’t hesitate to reach out to us.

Kind regards,

Martin Wierenga
CT-NetService

T: (+44) 0330 1241256
[callus]<https://pbxct-netservice.3cx.net/join/martin>

[Website]<http://www.ct-netservice.com/> [Email] <mailto:info@ct-netservice.com>
[Facebook]<https://www.facebook.com/pages/CT-NetService/305120189611653> [Twitter] <https://www.twitter.com/ctnetservice/>
________________________________
[cid:image008.jpg@01D4133A.80567E50]       [cid:image002.jpg@01CF6FD0.2E1061E0]         [cid:image010.jpg@01D4133A.80567E50]         [cf-certified-partner-badge-150px-lightbackgrounds]
________________________________
[green-printing]
