### ISSUE TITLE
After install not working on DNSonly 11.72 "failed all combinations" (debug logs)

### ISSUE THREAD

**Issue by kakarata** [letsencrypt-cpanel/letsencrypt-cpanel-dnsonly#8]
Using DNSonly 11.72 (last stable), then installed as:
https://dnsonly.letsencrypt-for-cpanel.com/

But after all process acmetool failed. I don't know if script is updated or not, some differences on what is trying to do acmetool and what it is installed on 11.72 version I think.

Debug output:

root@xx [/usr/local/letsencrypt-cpanel-dnsonly]#  /usr/local/letsencrypt-cpanel-dnsonly/acmetool --xlog.severity=debug reconcile    
20180824112114 [DEBUG] acme.storageops: Target(host.domain.example;https://acme-v01.api.letsencrypt.org/directory;0): best certificate satisfying is <nil>, err=Target(host.domain.example;https://acme-v01.api.letsencrypt.org/directory;0): no certificate satisfies this target
20180824112114 [DEBUG] acme.storageops: Target(host.domain.example;https://acme-v01.api.letsencrypt.org/directory;0): requesting certificate
20180824112114 [DEBUG] acme.api: request: https://acme-v01.api.letsencrypt.org/directory
20180824112115 [DEBUG] acme.api: response: &{200 OK 200 HTTP/1.1 1 1 map[Expires:[Fri, 24 Aug 2018 14:21:15 GMT] Pragma:[no-cache] Date:[Fri, 24 Aug 2018 14:21:15 GMT] Server:[nginx] Content-Type:[application/json] Content-Length:[658] Replay-Nonce:[OljtVqajiY9Doz4PRPq3csY62T25rpKjZMnlpkVM82M] X-Frame-Options:[DENY] Strict-Transport-Security:[max-age=604800] Cache-Control:[max-age=0, no-cache, no-store] Connection:[keep-alive]] 0xc420040480 658 [] false false map[] 0xc420073d00 0xc420076000} <nil>
20180824112115 [DEBUG] acme.api: request: https://acme-v01.api.letsencrypt.org/acme/new-reg
20180824112115 [DEBUG] acme.api: response: &{409 Conflict 409 HTTP/1.1 1 1 map[Pragma:[no-cache] Server:[nginx] Content-Type:[application/problem+json] Content-Length:[107] Location:[https://acme-v01.api.letsencrypt.org/acme/reg/40795543] Expires:[Fri, 24 Aug 2018 14:21:15 GMT] Cache-Control:[max-age=0, no-cache, no-store] Boulder-Requester:[40795543] Replay-Nonce:[mQBa3QvBJvb5R1ubayI6GY7uvuQVpUdg1rC2JLc2Ysw] Date:[Fri, 24 Aug 2018 14:21:15 GMT]] 0xc420040740 107 [] true false map[] 0xc4201bcc00 0xc420076000} <nil>
20180824112115 [DEBUG] acme.api: request: https://acme-v01.api.letsencrypt.org/acme/reg/40795543
20180824112116 [DEBUG] acme.api: response: &{202 Accepted 202 HTTP/1.1 1 1 map[Connection:[keep-alive] Server:[nginx] Content-Type:[application/json] Content-Length:[961] Boulder-Requester:[40795543] Cache-Control:[max-age=0, no-cache, no-store] Link:[<https://acme-v01.api.letsencrypt.org/acme/new-authz>;rel="next" <https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf>;rel="terms-of-service"] Replay-Nonce:[W6rcrSvNff_WWI94Woe5Kvv0ViIE5SfRTxOxFYVJSfM] Expires:[Fri, 24 Aug 2018 14:21:16 GMT] Pragma:[no-cache] Date:[Fri, 24 Aug 2018 14:21:16 GMT]] 0xc420150700 961 [] false false map[] 0xc4201bd000 0xc4202e6630} <nil>
20180824112116 [DEBUG] acme.storageops: trying to obtain authorization for "host.domain.example"
20180824112116 [DEBUG] acme.api: request: https://acme-v01.api.letsencrypt.org/acme/new-authz
20180824112117 [DEBUG] acme.api: response: &{201 Created 201 HTTP/1.1 1 1 map[X-Frame-Options:[DENY] Date:[Fri, 24 Aug 2018 14:21:17 GMT] Content-Length:[996] Location:[https://acme-v01.api.letsencrypt.org/acme/authz/XQeTiKgnrubi8ZzXJvpP6jcKNYOYcNWNihuW5VTOisg] Replay-Nonce:[umlMs_f6I2hUrFrDQyP05aXRmdqCIekrMaqp05M35GE] Boulder-Requester:[40795543] Expires:[Fri, 24 Aug 2018 14:21:17 GMT] Connection:[keep-alive] Server:[nginx] Content-Type:[application/json] Pragma:[no-cache] Link:[<https://acme-v01.api.letsencrypt.org/acme/new-cert>;rel="next"] Strict-Transport-Security:[max-age=604800] Cache-Control:[max-age=0, no-cache, no-store]] 0xc420150a80 996 [] false false map[] 0xc4201bdd00 0xc4202e6630} <nil>
20180824112117 [DEBUG] acme.solver: attempting challenge type http-01
20180824112117 [DEBUG] acme.responder: failed to listen on [::]:80: listen tcp [::]:80: bind: address already in use
20180824112117 [DEBUG] acme.responder: failed to listen on :80: listen tcp :80: bind: address already in use
20180824112117 [DEBUG] acme.responder: listening on [::1]:402
20180824112117 [DEBUG] acme.responder: listening on 127.0.0.1:402
20180824112117 [DEBUG] acme.responder: listening on [::1]:4402
20180824112117 [DEBUG] acme.responder: listening on 127.0.0.1:4402
20180824112117 [DEBUG] acme.responder: writing 1 webroot challenge files
20180824112117 [DEBUG] acme.responder: writing webroot file /var/run/acme/acme-challenge/v_69p3mIkL2T9kjeb1VNop_yycAc0glIo8lxk_KLsUE
20180824112117 [DEBUG] acme.hooks: calling hook script: /usr/libexec/acme/hooks/certificate-hook.sh
20180824112117 [DEBUG] acme.hooks: calling hook script: /usr/libexec/acme/hooks/reload
20180824112117 [DEBUG] acme.responder: http-01 self test
20180824112122 [INFO] acme.responder: http-01 self test failed: Get http://host.domain.example/.well-known/acme-challenge/v_69p3mIkL2T9kjeb1VNop_yycAc0glIo8lxk_KLsUE: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
20180824112122 [DEBUG] acme.responder: removing webroot file /var/run/acme/acme-challenge/v_69p3mIkL2T9kjeb1VNop_yycAc0glIo8lxk_KLsUE
20180824112122 [DEBUG] acme.hooks: calling hook script: /usr/libexec/acme/hooks/certificate-hook.sh
20180824112122 [DEBUG] acme.hooks: calling hook script: /usr/libexec/acme/hooks/reload
20180824112122 [DEBUG] acme.solver: challenge start failed: Get http://host.domain.example/.well-known/acme-challenge/v_69p3mIkL2T9kjeb1VNop_yycAc0glIo8lxk_KLsUE: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
20180824112122 [DEBUG] acme.solver: attempting challenge type dns-01
20180824112122 [DEBUG] acme.hooks: calling hook script: /usr/libexec/acme/hooks/certificate-hook.sh
20180824112122 [DEBUG] acme.hooks: calling hook script: /usr/libexec/acme/hooks/reload
20180824112122 [DEBUG] acme.solver: challenge start failed: could not install DNS challenge, no hooks succeeded
20180824112122 [ERROR] acme.storageops: could not obtain authorization for host.domain.example: failed all combinations
20180824112122 [ERROR] acme.storageops: Target(host.domain.example;https://acme-v01.api.letsencrypt.org/directory;0): failed to request certificate: failed all combinations
20180824112122 [DEBUG] acme.storageops: done processing targets, reconciliation complete, 1 errors occurred
20180824112122 [ERROR] acme.storageops: error while processing targets: the following errors occurred:
error satisfying Target(host.domain.example;https://acme-v01.api.letsencrypt.org/directory;0): failed all combinations
20180824112122 [ERROR] acme.storageops: failed to reconcile: the following errors occurred:
error satisfying Target(host.domain.example;https://acme-v01.api.letsencrypt.org/directory;0): failed all combinations
20180824112122 [DEBUG] acme.storageops: disjoint hostname mapping: host.domain.example -> Target(host.domain.example;https://acme-v01.api.letsencrypt.org/directory;0)
20180824112122 [DEBUG] acme.storageops: could not find certificate satisfying Target(host.domain.example;https://acme-v01.api.letsencrypt.org/directory;0): Target(host.domain.example;https://acme-v01.api.letsencrypt.org/directory;0): no certificate satisfies this target
20180824112122 [CRITICAL] acmetool: fatal: reconcile: the following errors occurred:
error satisfying Target(host.domain.example;https://acme-v01.api.letsencrypt.org/directory;0): failed all combinations

Any help will be much appreciated.
Thanks!

**Comment by eggsampler** [comment]
Are you running any sort of httpd on this DNSONLY server? The acmetool has failed to bind to http ports for challenge verification, which would indicate that something else is running.

**Comment by kakarata** [comment]
I have 3 DNSonly installed and httpd is running on 3. Port 80 is open on FW too. Monin plugin installed, maybe that? But it is opening on 2087 port. I think default DNSonly installation has 80 used by httpd, probably not serving content there but used by apache.

 

What other methods to authenticate?

 

This is netstat from one of DNSonly server:

 

netstat -tunlp

Active Internet connections (only servers)

Proto Recv-Q Send-Q Local Address               Foreign Address             State       PID/Program name   

tcp        0      0 0.0.0.0:2082                0.0.0.0:*                   LISTEN      9526/cpsrvd (SSL) - 

tcp        0      0 0.0.0.0:2083                0.0.0.0:*                   LISTEN      9526/cpsrvd (SSL) - 

tcp        0      0 127.0.0.1:579               0.0.0.0:*                   LISTEN      9534/cPhulkd - proc 

tcp        0      0 0.0.0.0:2086                0.0.0.0:*                   LISTEN      9526/cpsrvd (SSL) - 

tcp        0      0 0.0.0.0:2087                0.0.0.0:*                   LISTEN      9526/cpsrvd (SSL) - 

tcp        0      0 127.0.0.1:199               0.0.0.0:*                   LISTEN      16049/snmpd         

tcp        0      0 0.0.0.0:3306                0.0.0.0:*                   LISTEN      12037/mysqld        

tcp        0      0 0.0.0.0:587                 0.0.0.0:*                   LISTEN      22458/exim          

tcp        0      0 0.0.0.0:2095                0.0.0.0:*                   LISTEN      9526/cpsrvd (SSL) - 

tcp        0      0 0.0.0.0:2096                0.0.0.0:*                   LISTEN      9526/cpsrvd (SSL) - 

tcp        0      0 0.0.0.0:465                 0.0.0.0:*                   LISTEN      22458/exim          

tcp        0      0 10.0.10.66:53               0.0.0.0:*                   LISTEN      11271/named         

tcp        0      0 127.0.0.1:53                0.0.0.0:*                   LISTEN      11271/named         

tcp        0      0 0.0.0.0:22                  0.0.0.0:*                   LISTEN      12197/sshd          

tcp        0      0 0.0.0.0:25                  0.0.0.0:*                   LISTEN      22458/exim          

tcp        0      0 127.0.0.1:953               0.0.0.0:*                   LISTEN      11271/named         

tcp        0      0 :::587                      :::*                        LISTEN      22458/exim          

tcp        0      0 :::80                       :::*                        LISTEN      829/httpd           

tcp        0      0 :::465                      :::*                        LISTEN      22458/exim          

tcp        0      0 :::4949                     :::*                        LISTEN      9352/perl           

tcp        0      0 :::22                       :::*                        LISTEN      12197/sshd          

tcp        0      0 :::25                       :::*                        LISTEN      22458/exim          

udp        0      0 10.0.10.66:53               0.0.0.0:*                               11271/named         

udp        0      0 127.0.0.1:53                0.0.0.0:*                               11271/named         

udp        0      0 0.0.0.0:161                 0.0.0.0:*                               16049/snmpd        

 

 

Thanks

 

 

De: Isaac <notifications@github.com> 
Enviado el: viernes, 24 de agosto de 2018 13:09
Para: letsencrypt-cpanel/letsencrypt-cpanel-dnsonly <letsencrypt-cpanel-dnsonly@noreply.github.com>
CC: kakarata <elkato@gmail.com>; Author <author@noreply.github.com>
Asunto: Re: [letsencrypt-cpanel/letsencrypt-cpanel-dnsonly] After install not working on DNSonly 11.72 "failed all combinations" (debug logs) (#8)

 

Are you running any sort of httpd on this DNSONLY server? The acmetool has failed to bind to http ports for challenge verification, which would indicate that something else is running.

**Comment by alexzorin** [comment]
Hi @kakarata,

I strongly suspect that this is not a DNSONLY server.

The giveaway is that DNSONLY servers do not listen on ports 2082/2083. That is access for non-privileged users, a concept that does not exist on DNSONLY servers.

Likewise, port 80 is also unused on DNSONLY.

I have verified this with a fresh cPanel 74 DNSONLY installation just now.

    [root@nsx ~]# ss -tlnp
    State       Recv-Q Send-Q  Local Address:Port                 Peer Address:Port
    LISTEN      0      45          127.0.0.1:579                             *:*                   users:(("cPhulkd - proce",pid=8593,fd=6))
    LISTEN      0      45                  *:2086                            *:*                   users:(("cpsrvd (SSL",pid=8198,fd=9))
    LISTEN      0      45                  *:2087                            *:*                   users:(("cpsrvd (SSL",pid=8198,fd=8))
    LISTEN      0      50                  *:3306                            *:*                   users:(("mysqld",pid=4523,fd=10))
    LISTEN      0      50                  *:587                             *:*                   users:(("exim",pid=8159,fd=8))
    LISTEN      0      128                 *:111                             *:*                   users:(("rpcbind",pid=479,fd=8))
    LISTEN      0      50                  *:465                             *:*                   users:(("exim",pid=8159,fd=6))
    LISTEN      0      10       172.30.1.216:53                              *:*                   users:(("named",pid=6272,fd=22))
    LISTEN      0      10          127.0.0.1:53                              *:*                   users:(("named",pid=6272,fd=21))
    LISTEN      0      128                 *:22                              *:*                   users:(("sshd",pid=6853,fd=3))
    LISTEN      0      50                  *:25                              *:*                   users:(("exim",pid=8159,fd=4))
    LISTEN      0      128         127.0.0.1:953                             *:*                   users:(("named",pid=6272,fd=23))
    LISTEN      0      50                 :::587                            :::*                   users:(("exim",pid=8159,fd=7))
    LISTEN      0      128                :::111                            :::*                   users:(("rpcbind",pid=479,fd=11))
    LISTEN      0      50                 :::465                            :::*                   users:(("exim",pid=8159,fd=5))
    LISTEN      0      128                :::22                             :::*                   users:(("sshd",pid=6853,fd=4))
    LISTEN      0      50                 :::25                             :::*                   users:(("exim",pid=8159,fd=3))

In the past I have accidentally installed full WHM/cPanel instead of DNSONLY - perhaps that is what has happened.

Closing as invalid.

**Comment by kakarata** [comment]
3 servers with DNSonly as showed. Installed since 11.46 or 11.48 and was being updated each 1 or 2 releases. This week to last stable. 3 servers look and work the same.

 

Installed on LXC/Proxmox. I have cpanel support, in case you don’t think this is cpanel dnsonly, please let me know how can I get the info from them, but please don’t close this issue. Could be helpful to many others.

thanks

 



 

De: alexzorin <notifications@github.com> 
Enviado el: viernes, 24 de agosto de 2018 19:20
Para: letsencrypt-cpanel/letsencrypt-cpanel-dnsonly <letsencrypt-cpanel-dnsonly@noreply.github.com>
CC: kakarata <elkato@gmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [letsencrypt-cpanel/letsencrypt-cpanel-dnsonly] After install not working on DNSonly 11.72 "failed all combinations" (debug logs) (#8)

 

Hi @kakarata <https://github.com/kakarata> ,

I strongly suspect that this is not a DNSONLY server.

The giveaway is that DNSONLY servers do not listen on ports 2082/2083. That is access for non-privileged users, a concept that does not exist on DNSONLY servers.

Likewise, port 80 is also unused on DNSONLY.

I have verified this with a fresh cPanel 75 DNSONLY installation just now.

In the past I have accidentally installed full WHM/cPanel instead of DNSONLY - perhaps that is what has happened.

Closing as invalid.

**Comment by alexzorin** [comment]
You can ask cPanel support why your DNSONLY servers are listening on ports 2083 and 80.

Unless your scenario can be corroborated by other users or cPanel support as a valid configuration, then I'm not willing to expand this package to support it.

**Comment by kakarata** [comment]
Ok, got it. I’ll check that.

thanks

 

De: alexzorin <notifications@github.com> 
Enviado el: viernes, 24 de agosto de 2018 19:45
Para: letsencrypt-cpanel/letsencrypt-cpanel-dnsonly <letsencrypt-cpanel-dnsonly@noreply.github.com>
CC: kakarata <elkato@gmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [letsencrypt-cpanel/letsencrypt-cpanel-dnsonly] After install not working on DNSonly 11.72 "failed all combinations" (debug logs) (#8)

 

You can ask cPanel support why your DNSONLY servers are listening on ports 2083 and 80.

Unless your scenario can be corroborated by other users or cPanel support as a valid configuration, then I'm not willing to expand this package to support it.
